### ISSUE TITLE
Contact Us contact details

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#27]
Hi Jason, 
Right under the banner image, we have our email address and phone number. I didn't think we need both yellow lines under each. I think we can list the phone number and then the email and then just one yellow line under that. Also, give it a little more breathing room between the number and the yellow line.
<img width="1010" alt="Screen Shot 2020-04-27 at 9 08 34 AM" src="https://user-images.githubusercontent.com/60756584/80394679-067bb100-8867-11ea-842c-6aac54fd9471.png">

**Comment by Herm71** [comment]
Center and make bigger. Lose the yellow.

**Comment by Herm71** [comment]
Fixed!

**Comment by Mirandapow** [comment]
Hi @Herm71,

This looks better, but I still don't think we need the yellow line under the phone number. Can we loose it?
<img width="296" alt="Screen Shot 2020-05-06 at 11 04 49 AM" src="https://user-images.githubusercontent.com/60756584/81212374-adf49400-8f89-11ea-9392-bed548dd68b2.png">
